name: Build

on: [push, workflow_call]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install 
    - run: npm run build
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
